#!/bin/bash

# Path to the database file
database_file="/home/sysop/Downloads/db.u8"
# Path to the output file
output_file="/home/sysop/Downloads/out.u8"

# Function to replace text after Chinese characters with correct transcription
replace_transcriptions() {
    local line
    while IFS= read -r line; do
        echo "Original Line: $line" >&2
        
        chinese_chars=$(echo "$line" | perl -C -pe 's/.*?([\x{4E00}-\x{9FFF}]).*/$1/')
        echo "Extracted Chinese Characters: $chinese_chars" >&2

        if [[ -n $chinese_chars ]]; then
            trans_line=$(grep "^$chinese_chars " "$output_file")
            echo "Matching Line: $trans_line" >&2
            
            if [[ -n $trans_line ]]; then
                new_transcription=$(echo "$trans_line" | awk '{ print $3 }')
                echo "New Transcription: $new_transcription" >&2

                line=$(echo "$line" | awk -v new_trans="$new_transcription" '{ sub(/.*/, new_trans); print }')
            fi
        fi

        echo "Modified Line: $line" >&2
        echo "---" >&2
        
        echo "$line" >&2
    done
}




# Read the file line by line and write the extracted data to temporary file
while IFS= read -r line; do
    # Skip comment lines starting with '#'
    if [[ $line =~ ^#.* ]]; then
        continue
    fi

    # Extract traditional and simplified
    TRADITIONAL=$(echo "$line" | awk -F ' ' '{print $1}')
    SIMPLIFIED=$(echo "$line" | awk -F ' ' '{print $2}')

    # Extract the transcription
    temp="${line}"
    TRANSCRIPTION=$(echo "$temp" | awk -F '[[]' '{print $2}' | awk -F ']' '{print $1}')

    # Extract the definitions
    DEFINITIONS=$(echo "$temp" | awk -F '/' '{for (i=2; i<=NF; i++) print $i}')

    # Reset TWTRANSCRIPTION
    TWTRANSCRIPTION=""

    # Check if TW transcription is present
    if [[ "$DEFINITIONS" == *"Taiwan pr. ["* ]]; then
        # Extract TW transcription
        TWTRANSCRIPTION=$(echo "$DEFINITIONS" | awk -F 'Taiwan pr. \\[' '{print $2}' | awk -F '\\]' '{print $1}' | tr -d '\n')
        # Make a new definition for TW centric entries
        TWDEFINITIONS=""
        TWDEFINITIONS=$(echo "$DEFINITIONS" | sed -E "s/Taiwan pr. \[(.+?)\]/PRC pr. [$TRANSCRIPTION]/g")
        # Update the original transcription with TWTRANSCRIPTION
        TRANSCRIPTION=$TWTRANSCRIPTION
    fi

    # Deal with newlines and format DEFINITIONS so it is back in the format of the original CC-CEDICT
    DEFINITIONS_SAVED=$(echo "$DEFINITIONS" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
    DEFINITIONS_SAVED="/${DEFINITIONS_SAVED//$'\n'//}/"

    # Write the extracted data to the temporary file
    if [[ -z "$TWTRANSCRIPTION" ]]; then
        echo "$TRADITIONAL  $SIMPLIFIED [$TRANSCRIPTION] $DEFINITIONS_SAVED"
    else
        echo "$TRADITIONAL  $SIMPLIFIED [$TWTRANSCRIPTION] $DEFINITIONS_SAVED"
    fi
done < "$database_file" | replace_transcriptions > "$output_file"

# Clean up temporary file
rm -f "$output_file.tmp"
